apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    qcloud-app: test
  name: test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      qcloud-app: test
  template:
    metadata:
      creationTimestamp: null
      labels:
        qcloud-app: test
    spec:
      containers:
      - args:
        - sleep
        - "100000"
        image: centos:latest
        imagePullPolicy: Always
        name: test
